### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by jackdehack**

### CODE REVIEW

**Comment by irhrhd** [comment]
Uh how about no

**Comment by jackdehack** [comment]
What?

**Comment by irhrhd** [comment]
No no no your trying to steal the credit so no

**Comment by jackdehack** [comment]
Lul buddy I did that 2 years ago for a school iPad unblocker. Couldn’t give a fuck if you deleted the whole thing bro lmaooo.

**Comment by irhrhd** [comment]
Hehehe what school ipad unblocker im on a school ipad and cant do shit

**Pull request closed without merging**
